### ISSUE TITLE
Index outside the bounds of the array when copying files

### ISSUE THREAD

**Issue by Qazzquimby** [Hypocrita20XX/Conexus#23]
[0000001] [1_30_2021_12_34_49_AM] INPUT: Mode switched to "Download Mods
[0000002] [1_30_2021_12_34_49_AM] INPUT: Method switched to "Steam Collection
[0000003] [1_30_2021_12_34_50_AM] VERIFY: Links.txt found
[0000004] [1_30_2021_12_34_50_AM] VERIFY: Loaded INI
[0000005] [1_30_2021_12_34_50_AM] VERIFY: No saved collection URL
[0000006] [1_30_2021_12_34_50_AM] VERIFY: Saved SteamCMD directory found, now showing on the UI
[0000007] [1_30_2021_12_34_50_AM] VERIFY: Saved mods directory found, now showing on the UI
[0000008] [1_30_2021_12_34_50_AM] VERIFY: Saved Steam username found, now showing (obscured) on the UI
[0000009] [1_30_2021_12_34_50_AM] VERIFY: Saved Steam password found, now showing (obscured) on the UI
[0000010] [1_30_2021_12_34_50_AM] VERIFY: Saved preferred method found: Steam collection
[0000011] [1_30_2021_12_34_50_AM] VERIFY: "Download Mods" has been set as the designated mode
[0000012] [1_30_2021_12_34_53_AM] INPUT: Method switched to "List"
[0000013] [1_30_2021_12_34_54_AM] INFO: Using Microsoft Windows NT 10.0.19041.0
[0000014] [1_30_2021_12_34_54_AM] INFO: Using supported Windows version, 10
[0000015] [1_30_2021_12_34_54_AM] INFO: Using a list of links
[0000016] [1_30_2021_12_34_54_AM] INFO: Mod info will now be obtained from the Links file
[0000017] [1_30_2021_12_34_54_AM] PROC: ModInfo contents have been ovewritten
[0000018] [1_30_2021_12_34_54_AM] PROC: Links.txt will now be parsed for mod info
[0000019] [1_30_2021_12_34_54_AM] INFO: Finished processing mod info in Links file
[0000020] [1_30_2021_12_34_54_AM] INFO: Mod info has been obtained, mods will now be downloaded
[0000021] [1_30_2021_12_34_54_AM] PROC: Commands will now be obtained
[0000022] [1_30_2021_12_34_54_AM] INFO: SteamCMD will take over now
[0000023] [1_30_2021_12_35_23_AM] PROC: Acquiring paths to copy from
[0000024] [1_30_2021_12_35_23_AM] PROC: Acquiring paths to copy to
[0000025] [1_30_2021_12_35_23_AM] PROC: Copying files, please wait
[0000026] [1_30_2021_12_35_23_AM] INFO: Files copied, original copy will now be deleted
[0000027] [1_30_2021_12_35_23_AM] WARNING: exception occured! Index was outside the bounds of the array.
[0000028] [1_30_2021_12_35_23_AM] WARNING: Please post your logs on Github! https://github.com/Hypocrita20XX/Conexus/issues

My links file contains
`*PATCHES
*Marvin Seo Mods: Shared Assets
https://steamcommunity.com/sharedfiles/filedetails/?id=1907321071
*Pet Store (Patch)
https://steamcommunity.com/sharedfiles/filedetails/?id=1895761375
*Librarian Optional Patch
https://steamcommunity.com/sharedfiles/filedetails/?id=1423881991
*Hard Earned Districts - Snake Charmer Patch
https://steamcommunity.com/sharedfiles/filedetails/?id=1487892262
*Hard Earned Districts - O'Nightmare Patch
https://steamcommunity.com/sharedfiles/filedetails/?id=1487892163
*Hard Earned Districts - Monk Patch
https://steamcommunity.com/sharedfiles/filedetails/?id=1487892033
*
*OVERHAULS
*Level 2 and 4 Quests
https://steamcommunity.com/sharedfiles/filedetails/?id=1469652546
*Crimson Court: Virulent Overhaul
https://steamcommunity.com/sharedfiles/filedetails/?id=1605546482
*
*SMALL GAMEPLAY CHANGES
*Banshee Boss Missions
https://steamcommunity.com/sharedfiles/filedetails/?id=1655297040
*Unique Stumble Icons
https://steamcommunity.com/sharedfiles/filedetails/?id=2048057940
*Mafe Patch for Quest Generation Issues
https://steamcommunity.com/sharedfiles/filedetails/?id=1889116980
*Quirk Expansion Pack by Marvin Seo
https://steamcommunity.com/sharedfiles/filedetails/?id=1907320682
*Grunt's Modded Fallen Heroes- Beta
https://steamcommunity.com/sharedfiles/filedetails/?id=1682605126
*
*REBALANCE
*Cho's Boss Reworks
https://steamcommunity.com/sharedfiles/filedetails/?id=1381021604
*Larger Roster
https://steamcommunity.com/sharedfiles/filedetails/?id=903716519
*Gyll's Vanilla: Shieldbreaker
https://steamcommunity.com/sharedfiles/filedetails/?id=1509926649
*Gyll's Vanilla: Flagellant
https://steamcommunity.com/sharedfiles/filedetails/?id=1408032394
*Gyll's Vanilla: Heroes
https://steamcommunity.com/sharedfiles/filedetails/?id=1385283735
*Hard Earned Districts - Districts Expansion
https://steamcommunity.com/sharedfiles/filedetails/?id=1487042047
*Hard Earned Districts
https://steamcommunity.com/sharedfiles/filedetails/?id=1487041709
*
*CONTENT ADDONS
*Bloat Class Mod-Trinket Pack
https://steamcommunity.com/sharedfiles/filedetails/?id=1990987273
*The Condemned Shack District Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=1984429072
*Kraken Society District Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=1979369788
*Sunward Expansion: The Night Parade
https://steamcommunity.com/sharedfiles/filedetails/?id=2115544857
*Sunward Isles: Marvin Seo Class Trinkets
https://steamcommunity.com/sharedfiles/filedetails/?id=1745548866
*Butcher bird COM trinket
https://steamcommunity.com/sharedfiles/filedetails/?id=1470566390
*Lamia Quirks Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=1912437803
*Sunward Isles: S-Purple Class Trinkets
https://steamcommunity.com/sharedfiles/filedetails/?id=1820077943
*Grove tender COM trinket
https://steamcommunity.com/sharedfiles/filedetails/?id=1835275005
*Grove tender CC trinket
https://steamcommunity.com/sharedfiles/filedetails/?id=1835274494
*Memorial Grounds District Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=1697038590
*The Rightful Heir - DLC trinkets
https://steamcommunity.com/sharedfiles/filedetails/?id=1649053980
*Cursed Ground District
https://steamcommunity.com/sharedfiles/filedetails/?id=1540158327
*Amphitheater District Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=1130844712
*The Tusk - CC Trinkets
https://steamcommunity.com/sharedfiles/filedetails/?id=1128338441
*The Offering -  CC Trinkets
https://steamcommunity.com/sharedfiles/filedetails/?id=1128411084
*The Hollow -  CC Trinkets
https://steamcommunity.com/sharedfiles/filedetails/?id=1128408705
*The Hood -  CC Trinkets
https://steamcommunity.com/sharedfiles/filedetails/?id=1157520943
*The Shrapnel -  CC Trinkets
https://steamcommunity.com/sharedfiles/filedetails/?id=1203644800
*The Profligates -  CoM Trinkets
https://steamcommunity.com/sharedfiles/filedetails/?id=1417061383
*Snake Charmer's Theater
https://steamcommunity.com/sharedfiles/filedetails/?id=1624244631
*Cataphract Crimson Court Trinkets
https://steamcommunity.com/sharedfiles/filedetails/?id=1236107114
*Kraken Society CoM- Cataphract/Omen Seeker/Slayer expansion
https://steamcommunity.com/sharedfiles/filedetails/?id=1436933049
*Marvin Seo's Crimson Court Trinkets
https://steamcommunity.com/sharedfiles/filedetails/?id=1440851204
*Marvin Seo's Color of Madness Trinkets
https://steamcommunity.com/sharedfiles/filedetails/?id=1416418524
*
*CONTENT
*Janissary Class Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=2377934884
*Abysssinker Class Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=2306606465
*Here Be Monsters: The Preacher
https://steamcommunity.com/sharedfiles/filedetails/?id=2375353330
*dragon's Duelist
https://steamcommunity.com/sharedfiles/filedetails/?id=2371334111
*Bone Courtier Class Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=2339581104
*The Corsair Class Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=2363386707
*The Stargazer Class Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=2363387321
*The Powder Keg Class Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=2248772895
*Exterminator
https://steamcommunity.com/sharedfiles/filedetails/?id=2336153147
*The Herald
https://steamcommunity.com/sharedfiles/filedetails/?id=2341439121
*The Stars Class Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=2360027730
*Here Be Monsters: The Fungal Satyr
https://steamcommunity.com/sharedfiles/filedetails/?id=2350342464
*The Ringmaster Class Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=2325415039
*The Philomath Class
https://steamcommunity.com/sharedfiles/filedetails/?id=2318789444
*The Eternal
https://steamcommunity.com/sharedfiles/filedetails/?id=2199841880
*The Salamander Class Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=2204287440
*Here Be Monsters: The Mariner
https://steamcommunity.com/sharedfiles/filedetails/?id=2272832029
*Major Arcana Trinkets
https://steamcommunity.com/sharedfiles/filedetails/?id=1307312524
*Bits & Pieces:A Monster Trinket Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=1952138339
*Armored Templars
https://steamcommunity.com/sharedfiles/filedetails/?id=2177984110
*The Wanderer
https://steamcommunity.com/sharedfiles/filedetails/?id=2195826550
*EC Dungeon backgrounds
https://steamcommunity.com/sharedfiles/filedetails/?id=1447858689
*Extra Weald Backgrounds
https://steamcommunity.com/sharedfiles/filedetails/?id=1445430215
*Extra Cove Backgrounds
https://steamcommunity.com/sharedfiles/filedetails/?id=1393689708
*The Practitioner
https://steamcommunity.com/sharedfiles/filedetails/?id=2203158200
*Unhooded Shrew Mini-boss
https://steamcommunity.com/sharedfiles/filedetails/?id=1470903789
*The Blackguard Class Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=2168009997
*Here Be Monsters: The Sea Slater
https://steamcommunity.com/sharedfiles/filedetails/?id=2194229283
*The Carnifex
https://steamcommunity.com/sharedfiles/filedetails/?id=2226318273
*Blazing Lord Class
https://steamcommunity.com/sharedfiles/filedetails/?id=2182716765
*The Fixer - Unleashing the Kraken
https://steamcommunity.com/sharedfiles/filedetails/?id=2258846078
*The Fixer - House of Piggies & Meat Boss
https://steamcommunity.com/sharedfiles/filedetails/?id=2258091535
*The Fixer - Army of Bones
https://steamcommunity.com/sharedfiles/filedetails/?id=2257922070
*Myconidae plus
https://steamcommunity.com/sharedfiles/filedetails/?id=2255153973
*The Arsonist Class Mod **RE-UPLOADED**
https://steamcommunity.com/sharedfiles/filedetails/?id=2255822193
*Iron Man
https://steamcommunity.com/sharedfiles/filedetails/?id=1876423255
*The Marcus Brothers
https://steamcommunity.com/sharedfiles/filedetails/?id=2169361948
*The Haruspex
https://steamcommunity.com/sharedfiles/filedetails/?id=2057748143
*The Eucharistan
https://steamcommunity.com/sharedfiles/filedetails/?id=2077870092
*Rescuer (Class Mod)
https://steamcommunity.com/sharedfiles/filedetails/?id=2053917390
*The Nest District
https://steamcommunity.com/sharedfiles/filedetails/?id=2049964563
*The Rightful Heiress
https://steamcommunity.com/sharedfiles/filedetails/?id=2021307368
*More Hallway Variations
https://steamcommunity.com/sharedfiles/filedetails/?id=2020964465
*Koala's Creature Collection
https://steamcommunity.com/sharedfiles/filedetails/?id=2044162110
*Here Be Monsters: The Swine Chieftain
https://steamcommunity.com/sharedfiles/filedetails/?id=2024095844
*Forest Guardian's Altar -District
https://steamcommunity.com/sharedfiles/filedetails/?id=2010524553
*The Clobber 2.0 Serious Update
https://steamcommunity.com/sharedfiles/filedetails/?id=1867479147
*The Alchemist Class Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=2001406494
*The Steel-Driver Class Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=1999848432
*The Bloat Class Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=1990986165
*The Itinerant Cook
https://steamcommunity.com/sharedfiles/filedetails/?id=1978083682
*Beyond Mortality by Golden Yak
https://steamcommunity.com/sharedfiles/filedetails/?id=1960445714
*Bogatyr Class Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=1976300413
*warrens background pack
https://steamcommunity.com/sharedfiles/filedetails/?id=2084830422
*The Exile - Class Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=2101866853
*Singleplayer Circus Trinkets
https://steamcommunity.com/sharedfiles/filedetails/?id=2129157917
*Here Be Monsters: The Brigand Treasurer
https://steamcommunity.com/sharedfiles/filedetails/?id=2132041553
*The Raiju: A Sunward Addon
https://steamcommunity.com/sharedfiles/filedetails/?id=2133515740
*The Scarecrow (Class Mod)
https://steamcommunity.com/sharedfiles/filedetails/?id=2104150657
*Here Be Monsters: The Gallows Tree
https://steamcommunity.com/sharedfiles/filedetails/?id=2121063677
*Lord's Blade
https://steamcommunity.com/sharedfiles/filedetails/?id=1433161277
*Abysswalker
https://steamcommunity.com/sharedfiles/filedetails/?id=1225113804
*Additional Room Backgrounds
https://steamcommunity.com/sharedfiles/filedetails/?id=2064755795
*Dragonslayer
https://steamcommunity.com/sharedfiles/filedetails/?id=1207974198
*The Claimants-Class Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=2091777102
*Zenith (Class Mod)
https://steamcommunity.com/sharedfiles/filedetails/?id=2111344032
*Darkest Dungeon Senua Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=2016855256
*Shield Maiden - Class Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=963658853
*More dungeon background variations - Crimson Court add on
https://steamcommunity.com/sharedfiles/filedetails/?id=1448707567
*More dungeon background variations all in one- Reworked
https://steamcommunity.com/sharedfiles/filedetails/?id=1434609021
*Lumberjack Miniboss
https://steamcommunity.com/sharedfiles/filedetails/?id=1879840996
*Abyssal Horror Miniboss
https://steamcommunity.com/sharedfiles/filedetails/?id=1938759986
*Ashen Warrior - New Class
https://steamcommunity.com/sharedfiles/filedetails/?id=1946681830
*Sven, The Rogue Knight - Class Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=1945734076
*Divinity Remastered
https://steamcommunity.com/sharedfiles/filedetails/?id=1922669061
*The Apostate Class Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=1917819568
*The Mambo Hero Class mod
https://steamcommunity.com/sharedfiles/filedetails/?id=1865154690
*Grove tender Class Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=1835237651
*Harlot (Class Mod)
https://steamcommunity.com/sharedfiles/filedetails/?id=1860840141
*The Wretch Class Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=1849364138
*The Darkwraith
https://steamcommunity.com/sharedfiles/filedetails/?id=1825622538
*Arcanist
https://steamcommunity.com/sharedfiles/filedetails/?id=1800025310
*The Thorn
https://steamcommunity.com/sharedfiles/filedetails/?id=1785514611
*Pets 2 (Trinket + Monster Mod)
https://steamcommunity.com/sharedfiles/filedetails/?id=1779509342
*The Beastmaster
https://steamcommunity.com/sharedfiles/filedetails/?id=1747389796
*Duchess Class Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=1744414212
*Marvin Seo's Wraith Class Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=1697037179
*The Sunward Isles (New Dungeon)
https://steamcommunity.com/sharedfiles/filedetails/?id=1689234891
*The Barbarian: by Ahmonza
https://steamcommunity.com/sharedfiles/filedetails/?id=1686591937
*The Keeper Class Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=1688250816
*Butcher Bird Class Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=1447972888
*The Twilight Knight
https://steamcommunity.com/sharedfiles/filedetails/?id=1154908982
*Homunculus / Class mod 1.7
https://steamcommunity.com/sharedfiles/filedetails/?id=1665671496
*Guqin Class Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=1446914431
*Omen Seeker Class Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=1289815222
*Sea Serpent - Miniboss Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=1656363710
*Nerub
https://steamcommunity.com/sharedfiles/filedetails/?id=1656676055
*Head Hoarder - Warrens Miniboss
https://steamcommunity.com/sharedfiles/filedetails/?id=1656461307
*The Incandescent Whisperer
https://steamcommunity.com/sharedfiles/filedetails/?id=1655994081
*Slayer Class Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=1429069819
*Clair's Collection of Curiosities
https://steamcommunity.com/sharedfiles/filedetails/?id=1076447626
*The Banshee by Marvin Seo and Clair de Lune
https://steamcommunity.com/sharedfiles/filedetails/?id=1655294502
*'81 NEW TRINKETS!' Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=1319280399
*The Rightful Heir
https://steamcommunity.com/sharedfiles/filedetails/?id=1649053641
*Moonlit Dungeon - Ruins Enemy Pack
https://steamcommunity.com/sharedfiles/filedetails/?id=1641811807
*Unique Items : Mega Trinkets Pack
https://steamcommunity.com/sharedfiles/filedetails/?id=965846410
*Cannoneer - Class Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=912030977
*Monk Class Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=1442225067
*The Succubus
https://steamcommunity.com/sharedfiles/filedetails/?id=1597176026
*The Voivode - Reworked
https://steamcommunity.com/sharedfiles/filedetails/?id=1533032528
*The Exorcist Class Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=1607991008
*The Snake Charmer
https://steamcommunity.com/sharedfiles/filedetails/?id=1456853110
*The Fool -  Class Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=1464177353
*The Hood -  Class Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=1157520643
*The Shrapnel -  Class Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=1203645088
*The Librarian: Community Project
https://steamcommunity.com/sharedfiles/filedetails/?id=1185211485
*The Offering 2.0 - Class Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=1119908263
*The Hollow -  Class Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=1115865609
*The Fawn -  Remastered
https://steamcommunity.com/sharedfiles/filedetails/?id=1109179698
*The Tusk - Class Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=1123633838
*Cataphract Class Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=1235319270
*Marvin Seo's Sisters Class Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=1440822424
*Marvin Seo's Seraph Class Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=1221097087
*Marvin Seo's Thrall Class Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=1175904375
*Marvin Seo's Lamia Class Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=1130829365
*Marvin Seo's Falconer Class Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=1089257023
*Werewolf - New Class
https://steamcommunity.com/sharedfiles/filedetails/?id=1135620886`

**Comment by Qazzquimby** [comment]
Sorry, just noticed the links file pasted wrong. In my txt the comments and urls are on separate lines

**Comment by Hypocrita20XX** [comment]
Hey there, I'm really sorry I'm just now seeing this!
I have no idea why I didn't get a notification.

Just saw this a few moments ago and I'll be looking into this tonight, but wanted to at least comment and let you know I finally saw this.
Again, apologies for the delay!

**Comment by Hypocrita20XX** [comment]
Seems like this was hopefully an easy fix. Let me know if this works for you. =-)

https://github.com/Hypocrita20XX/Conexus/releases/tag/v1.3.1

**Comment by Qazzquimby** [comment]
Sorry now it's my turn to not notice the message.
New error, hopefully after the last one.
`Could not find a part of the path 'D:\Program Files\steamcmd\steamapps\workshop\content\262060'.`
This is fair since that path doesn't exist. I have `'D:\Program Files\steamcmd\steamapps\` but that folder contains only `libraryfolders.vdf`, my normal steamapps folder is somewhere else. 

I expect this is either a matter of a path not being set/overridden correctly, or its supposed to create nonexistent folders before working in them?
[2_9_2021_11_13_26_AM.txt](https://github.com/Hypocrita20XX/Conexus/files/5953787/2_9_2021_11_13_26_AM.txt)

**Comment by Hypocrita20XX** [comment]
Actually I'm fairly certain this is because your path has a space, D:\Program Files.
Try D:\steamcmd and let me know how that goes. =-)
I'll see if I can bundle a fix into this release later on.

#22

**Comment by Hypocrita20XX** [comment]
[Release Candidate 2 - 1.3.1.zip](https://github.com/Hypocrita20XX/Conexus/files/5954127/Release.Candidate.2.-.1.3.1.zip)

Alright, give this a try. =-)

**Comment by Qazzquimby** [comment]
On the second candidate, `Could not find a part of the path 'D:\steamcmd\steamapps\workshop\content\262060'.`
It might be important that that path really does not exist. Is it supposed to be created, or is it supposed to work in my regular steam folder?

**Comment by Hypocrita20XX** [comment]
Do you have the full log? I looked again at the last one you sent, and would like to compare, see if it broke in the same spot.
Thanks!

**Comment by Qazzquimby** [comment]
[2_9_2021_8_54_10_PM.txt](https://github.com/Hypocrita20XX/Conexus/files/5960679/2_9_2021_8_54_10_PM.txt)

**Comment by Hypocrita20XX** [comment]
A couple things.
Try clearing out everything in SteamCMD\SteamApps\Workshop\Content\262060 and DarkestDungeon\mods.
Then run Conexus again, make sure to run in Download Mods mode. Either method should work, collection or list.
Seems to me like something has gotten messed up along the way, I'm unable to recreate the issue at this point.


The versioning comments were implemented because I wanted to, at a glance, get a sense of what I did at any given point in time. I'm unfortunately not well-versed in versioning and only really can use it on a basic level at this point, and am unaware how well-integrated it is in Visual Studio.

I'm not too clear on what you mean by a logging library, and even less clear on how such a system would be implemented.
I should be up-front: I'm not at all a trained programmer, never been taught, this is all just a hobby. Almost entirely self-taught, so a lot of stuff just goes over my head and is unknown to me.

I'll have to look into that leading zeroes page a bit more in-depth later, definitely looks like a more elegant solution.


I appreciate the input!

**Comment by Hypocrita20XX** [comment]
So first of all, an apology: I've started taking some new medication lately and it has severely affected my ability to think clearly.
I've been providing absolutely awful troubleshooting this entire time, overlooking and not understanding a lot of what you've been saying.
I'll try to at least start remedying that now, to the best of my ability, and again, my apologies.


The root problem seems to be that Conexus isn't finding any valid mod info.
Here's a snippet from your latest log:
> INFO: Using a list of links
> INFO: Mod info will now be updated
> PROC: ModInfo contents have been ovewritten
> PROC: Links.txt will now be parsed for mod info
> INFO: Finished processing mod info in Links file

Here's a snippet from one of my logs using a list of links:
> PROC: Links.txt will now be parsed for mod info
> PROC: Found mod info in Links file: 000_1911326199
> PROC: Found mod info in Links file: 001_879079478
> ...
> PROC: Found mod info in Links file: 055_1429720281
> INFO: Finished processing mod info in Links file

I'm almost positive this is the root problem: no valid mod info found, Conexus attempts to process non-existent mod info, breaks in the process.

As to why this happens, several possibilities.
What I need to see is what your output is mentioned here: #21 
Is this still the method used for getting your list of mods?
If so, it would definitely help if you could send that result.

Here's a list of five mods, I know on my end that this works, if you could, please try this and let me know how it goes.
You'll need to clear out whatever may be in your steamcmd\steamapps\workshop\content\262060 and darkestdungeon\mods folders before doing so, to be sure it has the best chance to work (I still don't quite know how well Conexus works with remnants of older, unused modlists and don't have anything in place to automatically handle that kind of cleanup.)
[Links.txt](https://github.com/Hypocrita20XX/Conexus/files/5962843/Links.txt)

That folder that is being mentioned in the exception, for clarity, steamcmd\steamapps\workshop\content\262060, will be automatically created so long as mods are successfully downloaded. If mods cannot be downloaded for any reason, this folder won't be created.
Reasons include, but are not limited to, failed login, game not registered to the account (only applicable to certain games), incorrect commands.
In your case, I'm thinking incorrect commands based on what I was able to finally catch on to in your log.


Hopefully I can finally get you on the right track here.

**Comment by Hypocrita20XX** [comment]
Issue is thankfully resolved. For the benefit of those seeing this at a later time, we spoke on Discord and discovered that Links.txt was stored in the pre-1.3.0 location, darkestdungeon\mods, not in Documents\Conexus\Links.
