### ISSUE TITLE
Conexus downloading error with Steam Collection

### ISSUE THREAD

**Issue by Kevintron20** [Hypocrita20XX/Conexus#9]
Hello,

I have the same issue as Mr. Satan Senpai described on the Youtube tutorial for version 1.1.13. 
I have attached the txt files that were generated in the _DD_TextFiles folder in my mods folder. I would like to add that in the mods folder the first mod had a folder generated for it, but nothing was in the folder.

I also had the same "appworkshop_262060.acf" file generated in my SteamCMD folder even when I manually made a 262060 folder for the worshop files to go into. Another thing is that this file didn't generate when I was attempting to download with my collection when it was hidden and instead Conexus/steamcmd(I don't know which) created a 262060 folder instead of the .acf file.

One last thing to add is that when I tried troubleshooting by deleting all the files in the SteamCMD folder and reinstalling I noticed that SteamCMD appeared to crash once while installing and then restated the installation, and this happend the other 2 times I tried troubleshooting by deleting SteamCMD along with deleting all the files in the appdata/mods/262060 folders. 

[_DD_TextFiles.zip](https://github.com/Hypocrita20XX/Conexus/files/5816462/_DD_TextFiles.zip)

**Comment by Hypocrita20XX** [comment]
Hey there. =-)

First thing to check is visibility of the collection. Looks like you tried hidden? Conexus and SteamCMD can only work with collections set to unlisted or public. Unfortunately if set to to hidden or friends-only, the process won't work.

Which OS are you using, Windows 10? If not, I'm unsure I can be of much help. A Linux build is something I may be able to do at some point, but it's not currently one of my goals.

Looking at your files, nothing seems out of place, so at least part of the process is working as intended.

Don't know if you saw this in one of my comments, but I'll copy/paste verbatim just in case:
1.) Clear out any folder that may be in AppData. 
First you'll need to type in %AppData%, it'll put you in AppData\Roaming. Navigate back to AppData, then to AppData\Local. You should see Conexus listed here. Inside that folder, you'll see a folder named something like Conexus exe_url, delete that.
2.) Clear out any data in SteamCMD's workshop directory.
This is located in steamcmd\steamapps\workshop\content\262060, if the folder isn't empty, delete everything in it.
3.) Clear out any data in DarkestDungeon's mods directory.
This one's located in steam\steamapps\common\DarkestDungeon\mods, if that's not empty, delete all of that.
4.) Do a clean reinstall of steamcmd.
Thankfully pretty simple, just delete everything in steamcmd's root folder, put a clean copy of the exe and reinstall according to what's on the wiki (https://developer.valvesoftware.com/wiki/SteamCMD)

It's important that you do 1-3 all at once. If those fail, then repeat 1-3 and do 4 as well.


I have some ideas, but I'll need to think on this a bit more.
Let me know if any of the above changes the outcome.

**Comment by Kevintron20** [comment]
Sorry I should have been more clear, when I first attempted using Conexus the collection was on hidden, which is when I saw the 262060 folder created, but then I switched to public and did the above troubleshooting; that is when I saw the "appworkshop_262060.acf" file and no folder was created(the folder was deleted because I reinstalled SteamCMD). I then tried this again with the collection being unlisted and the same thing happend with the acf file being created instead of a folder.

I encounted the same thing Mr. Satan Senpai did with the same ERROR msg over and over for each mod in my collection.

Also I am running Windows 10.

**Comment by Hypocrita20XX** [comment]
That's alright, stuff slips our minds at times. 
Yeah, this is exactly what he's been telling me as well, so it's good to know it's not just one person.

I'll be looking further into this, and I'll get back to you with some hopefully good news later on. =-)
Apologies that you're having this issue!

**Comment by Hypocrita20XX** [comment]
Finally a breakthrough, I should have a fix sometime today/early tomorrow (unless more things break along the way.)

Almost certain this is a direct cause of anonymous login. What seems to happen is SteamCMD doesn't register that you own the game, and as such fails to download anything (I'm guessing this is an anti-piracy feature.)
I still have to test what happens when trying to do this with a copy from other platforms, GOG, Epic.
Once I get it working for Steam, I'll move on to Epic. I don't have it on GOG, so I can't test for that platform. 
Hopefully GOG will behave the same as Epic.

The fix will, at the very least, unfortunately require y'all to provide your Steam credentials to Conexus.
Thankfully this information will be saved locally only, and not shared online at all.
There may be other stuff I need to do so I can ensure this works, but we'll see.

**Comment by Kevintron20** [comment]
Ok, thanks for the update! I own it on steam so I cannot help with the Epic/GOG side of things when it comes to testing for it, but I'l let you know once you get the update ready for Conexus if I got it to work on my end.

**Comment by Hypocrita20XX** [comment]
Good news! I have a test build that I'm hoping will fix the problem.

You'll have to provide your steam login information now, everything is stored locally on your machine, nothing shared online, so it's secure. Some have had issues with that in the past, but if you trust SteamCMD, you can trust this. 
Also added a privacy feature, so when you add that info, it's obscured. You can reveal it at any time with the checkbox next to the username and password text fields.
It will probably ask for a Steam Guard code when you try downloading, just so you know.

You shouldn't have to reinstall SteamCMD, however making sure AppData and the DarkestDungeon\mods directory are empty would be for the best.
There are some unfinished features in this build, so I'm hoping those won't give you any issue. Also haven't tested Epic, so I've only validated using a Steam collection and owning it on Steam.

https://www.mediafire.com/file/1n6rmmom2pjrndu/Conexus_1.2.0_-_Release_Candidate_%2528001%2529.zip/file

**Comment by Kevintron20** [comment]
So a small update, I was able to get Conexus to work and begin downloading the mods from my collection. but it crashed about 1/4 of the way through the list(~40ish/150) so I am going to clear my mods folder/appdata again and see if it crashes again.

**Comment by Kevintron20** [comment]
Ok so it worked the second time but I had to clean up a bit after Conexus crashed(left some .acf files in other areas outside of the mod folder), but it all seems to be working. My only question remaining is that since I still have my mods installed via the workshop on steam(in my steam library's folder not the cmd one) do I need to delete those to ensure my game uses the mods directly in the mods folder, or since there are now files in the mods folder will it use those now?

**Comment by Hypocrita20XX** [comment]
Glad you got everything figured out. =-)
I would say to be safe, clear that out as well.
